version: '3'
networks:
  example:

services:
  db:
    container_name: pepega-bot-pg-db
    hostname: db
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    networks:
      - example
    ports:
      - '5432:5432'
  bot:
    container_name: pepega-bot
    environment:
      DB_PORT: 5421
      DB_USER: docker
      DB_PW: docker
      DB_DB: docker
      DB_HOST: db
    env_file:
      - prod.env
    networks:
      - example
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: .
